### ISSUE TITLE
Pop!_OS drivers not executing under Ubuntu install [GPD Win Max]

### ISSUE THREAD

**Issue by flubberglubber** [al12gamer/gpdwinlinux#2]
New to linux, so forgive me for this spotty info,
As far as I understand it, popos doesn't use the same apps that ubuntu does with regards to edid files, or grub. I believe kernelstub has something to do with it, but in any event I've been unable to get the touchscreen working correctly using your ubuntu_winmax.sh script. I have tried after upgrading from the ubuntu mate 20.04 image with all the win max drivers. I have tried prior using the same ideas as your script, just not automated in a fresh install of popos, with no resolution to the issues.
Currently with my upgraded system from mate, I have the screen resolution working properly, as the rest of the drivers, save for the touchscreen input calibration. I can find the info using xinput in terminal and it lists my touchscreen as id=14 with the driver as "/dev/input/event6" but from I've understanding is that if I were somehow able to configure event6, it would not be the solution I was looking for. With popos being as new as it is, getting info about it isn't pulling up much so I was hoping you'd be able to shed some light on the situation.

**Comment by al12gamer** [comment]
Have you tried it on 22.04?

**Comment by al12gamer** [comment]
With recent releases, is this working for you again?

**Comment by flubberglubber** [comment]
I have sold that device off some time back, and have no means to verify.
